document.querySelector("#name_me").innerHTML="Fabrício Rodrigues Pereira";
document.querySelector("#age_me").innerHTML="25 anos de Idade";
document.querySelector("#state_me").innerHTML="Minas Gerais";
document.querySelector(".me__foto").setAttribute("src", "assets/foto-rosto-mini.jpg");
document.querySelector("#name_band").innerHTML="SABATON";
document.querySelector("#genre_band").innerHTML="Power Metal";
document.querySelector("#description_band").innerHTML="<strong>Sabaton</strong> é uma banda de Power Metal, eles se formaram em Falun, Suécia. A maioria de suas músicas são sobre heroismo em guerras. Link da <a href='https://metal.fandom.com/wiki/Sabaton' target='_blank'>fandom Wiki</a>. E link do <a href='https://www.youtube.com/channel/UCjQhd1APsd5NQhiVZV7GYzg' target='_blank'>youtube oficial</a> deles. O <a href='https://www.sabaton.net/'>site oficial</a>.";
document.querySelector("#music_list").innerHTML="Aqui tem uma pequena lista das minhas músicas favoritas.";
document.querySelector("#title_1").innerHTML="Sparta";
document.querySelector("#music_1").setAttribute("src","http://www.youtube.com/embed/hm-PT_FdAJU");
document.querySelector("#title_2").innerHTML="The Last Stand";
document.querySelector("#music_2").setAttribute("src","http://www.youtube.com/embed/HaTn3oRPtzg");
document.querySelector("#title_3").innerHTML="Fields of Verdun";
document.querySelector("#music_3").setAttribute("src","http://www.youtube.com/embed/xP8G-LwWNn0");
document.querySelector("#title_4").innerHTML="The Attack of the Dead Man";
document.querySelector("#music_4").setAttribute("src","http://www.youtube.com/embed/-AFdwoyNT24");
document.querySelector("#title_5").innerHTML="The Last Battle";
document.querySelector("#music_5").setAttribute("src","http://www.youtube.com/embed/BwfJsKfCnaM");
document.querySelector("#title_6").innerHTML="Smoking Snakes";
document.querySelector("#music_6").setAttribute("src","http://www.youtube.com/embed/cpW3RboCnzg");
document.querySelector("#image_1").setAttribute("src","assets/album-1.jpg");
document.querySelector("#image_2").setAttribute("src","assets/band-1.webp");
document.querySelector("#image_3").setAttribute("src","assets/band-2.jpg");
document.querySelector("#image_4").setAttribute("src","assets/album-2.webp");